### ISSUE TITLE
imgSlider on Mobile.

### ISSUE THREAD

**Issue by sinlesstiramisu** [kavyasukumar/imgSlider#2]
Hi, Wanted to know if there is a way for this to work as smoothly on the mobile. Currently its a charm on the desktop but the mobile experience is different. Thank You

**Comment by kavyasukumar** [comment]
@sinlesstiramisu Can you please share what version you are using and more details about the issue?
Are you seeing the same issue on http://kavyasukumar.com/apps/imgslider/ demo page?

UPDATE: i was able to repro the issue.  there is a missing distribution. i will update the plugin soon
