### ISSUE TITLE
Interested in change ?

### ISSUE THREAD

**Issue by ddorian** [kavyasukumar/imgSlider#5]
I can make a pull request that will execute a custom function inside slideResize() whenever it's called ?
This way, we can change other stuff on the page when the user moves the slider.

ok ?

**Comment by kavyasukumar** [comment]
@ddorian go for it. Sounds like a good option. I will review the PR once you have it

**Comment by ddorian** [comment]
Sorry didn't need to extend that after all. Such is life of open source.
